### ISSUE TITLE
Expansion Connector Sizing/Fit

### ISSUE THREAD

**Issue by BlipRanger** [jkua/wheelwriter-interface#2]
Howdy Jkua, great work on this project! I'm just getting started on fabrication and was wondering, how does the PCB you've designed fit in the little slot? Does it connect via a ribbon cable or is it meant to slot into the 70mm panel area somehow? Just trying to wrap my head around the design before I start milling. Thanks!

**Comment by jkua** [comment]
Hi! I've added some notes and images to the [pcb README](https://github.com/jkua/wheelwriter-interface/tree/main/pcb#v2---expansion-housing-pcb). The board is designed to attach to the expansion housing that came with the original expansion boards. It was a plastic housing that clipped onto the back of the Wheelwriter.

And yes, you'd need to build a cable to connect from the Wheelwriter expansion port to this interface board. I added the relevant part numbers to the README as well.

Please do note that I have not tested the v2 design! It's not a terribly complex design, but it's overengineered as I originally thought I had some noise problems with the prototype breadboard. Those issues turned out to be due to a counterfeit level translator I was using (don't buy ICs off random sellers on Amazon!). I'll eventually get around to assembling and testing the v2 design since I fabbed the board and purchased all the components, but future builds will likely go back to a simpler design more like the prototype breadboard.

**Comment by jkua** [comment]
Great! Please do report back! It is a very niche project with just a few people working on it, as far as I know. Hopefully more once this matures a bit.

> I got everything from Digikey, so hopefully no counterfits!
I've never had any problems with Digikey in all my years; I was just impatient (and cheap) this one time and it really bit me! It took awhile to figure out that that part was the problem and then I forgot about it since my work on the project is very intermittent!

I just got my Wheelwriter 3 back up and running as the solenoid cap on the print hammer had finally crumbled to dust.

**Comment by jkua** [comment]
Thanks for the report! I really appreciate it! Happy to hear that the board works!
